name    'apache-install'
version '0.1.0'
source 'UNKNOWN'
author 'Thopu Rupesh'
license 'Apache License, Version 2.0'
summary 'Install, Configure and Start Apache service on a remote server'
description 'Install, Configure and Start Apache service on a remote server'
project_page 'UNKNOWN'

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
